name:  boltstorm
title:  Boltstorm
version: "alpha-0.3.5"
summary:  Boltstorm is a game developed during Ludum Dare 34 game jam in 72 hours
description: |
  Boltstorm is a game developed during Ludum Dare 34 game jam in 72 hours. It is about a Knight that ventures into the dungeon to save his fellow knights, but instead he gets trapped and is attacked by merciless executioners! Theme of BoltStorm is growing. Goal is to Save the knights, and as your chain grows stronger survive the attack. Leveling up will increase your firing rate and add extra followers, but make the level more difficult while the enemy numbers increase.

grade: stable
icon: boltstorm_icon.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  boltstorm:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "Joust3_RevengeOfTheLavaTroll.exe"
      INSTALL_EXE: "$SNAP/BoltStorm-Alpha-0-3-5_PC.exe"
      #INSTALL_FLAGS: "/S"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: ./

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

